# Generated by Django 6.0.6 on 2026-08-29 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('provider_event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhooks_event',
                'indexes': [models.Index(fields=['provider', 'event_type', 'processed'], name='webhook_provider_type_idx'), models.Index(fields=['provider_event_id'], name='webhook_event_id_idx')],
            },
        ),
    ]
