# Generated by Django 6.0.6 on 2026-08-29 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('cover_image_url', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company')),
            ],
            options={
                'db_table': 'events_event',
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('doors_open', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.event')),
            ],
            options={
                'db_table': 'events_date',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'status'], name='event_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'created_at'], name='event_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdate',
            index=models.Index(fields=['event', 'start_datetime'], name='eventdate_event_start_idx'),
        ),
    ]
