# Generated by Django 6.0.6 on 2026-08-29 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('quantity_total', models.PositiveIntegerField()),
                ('quantity_held', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.event')),
            ],
            options={
                'db_table': 'inventory_tier',
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='tier_event_active_idx'), models.Index(fields=['event', 'price'], name='tier_event_price_idx')],
            },
        ),
    ]
