# Generated by Django 6.0.6 on 2026-08-29 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(default='Main', max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checkin', to='tickets.ticket')),
            ],
            options={
                'db_table': 'checkin_checkin',
                'indexes': [models.Index(fields=['ticket', 'scanned_at'], name='checkin_ticket_time_idx')],
            },
        ),
    ]
