# Generated by Django 6.0.6 on 2026-08-29 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('inventory', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='issued', max_length=20)),
                ('qr_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='checkout.checkouthold')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='payments.payment')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='inventory.tickettier')),
            ],
            options={
                'db_table': 'tickets_ticket',
                'indexes': [models.Index(fields=['tier', 'status'], name='ticket_tier_status_idx'), models.Index(fields=['attendee', 'status'], name='ticket_attendee_status_idx')],
            },
        ),
    ]
